# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: iptables
  state_top:
    base:
      "*":
        - iptables

platforms:
  - name: bento/debian-8

suites:
  - name: default
  
  - name: custom
    provisioner:
      pillars-from-files:
        iptables.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - iptables
